"""Add core models

Revision ID: 5f835e5027b5
Revises: 940b713441e2
Create Date: 2026-07-12 09:48:37.025141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f835e5027b5'
down_revision: Union[str, Sequence[str], None] = '940b713441e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('license_category', sa.String(), nullable=False),
    sa.Column('license_expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('Available', 'OnTrip', 'OffDuty', 'Suspended', name='driverstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_id'), 'driver', ['id'], unique=False)
    op.create_index(op.f('ix_driver_license_number'), 'driver', ['license_number'], unique=True)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('max_load_capacity', sa.Float(), nullable=False),
    sa.Column('odometer', sa.Float(), nullable=True),
    sa.Column('acquisition_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Available', 'OnTrip', 'InShop', 'Retired', name='vehiclestatus'), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_registration_number'), 'vehicle', ['registration_number'], unique=True)
    op.create_table('maintenancelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Closed', name='maintenancestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenancelog_id'), 'maintenancelog', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenancelog_id'), table_name='maintenancelog')
    op.drop_table('maintenancelog')
    op.drop_index(op.f('ix_vehicle_registration_number'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_driver_license_number'), table_name='driver')
    op.drop_index(op.f('ix_driver_id'), table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###
